services:
  mongo:
    image: mongo:7.0
    container_name: hpmbs_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: hpmbs_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27021:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hpmbs_backend
    restart: always
    environment:
      PORT: 5001
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/hpmbs_db
      JWT_SECRET: hpmbs_super_secret_jwt_key_2026_production_grade
      JWT_EXPIRES_IN: 7d
      REFRESH_TOKEN_SECRET: hpmbs_super_secret_refresh_key_2026_production_grade
      REFRESH_TOKEN_EXPIRES_IN: 30d
      CORS_ORIGIN: "*"
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hpmbs_frontend
    restart: always
    ports:
      - "85:80"
    depends_on:
      - backend

volumes:
  mongo_data:
