export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HOSPITAL_ADMIN: 'HOSPITAL_ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  NURSE_INCHARGE: 'NURSE_INCHARGE',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  LAB_TECH: 'LAB_TECH',
  RADIOLOGIST: 'RADIOLOGIST',
  CASHIER: 'CASHIER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  HR_MANAGER: 'HR_MANAGER',
  BILLING_STAFF: 'BILLING_STAFF',
  LABORATORY_STAFF: 'LABORATORY_STAFF',
  RADIOLOGY_STAFF: 'RADIOLOGY_STAFF',
  PHARMACY_STAFF: 'PHARMACY_STAFF',
  OPD_STAFF: 'OPD_STAFF',
  IPD_STAFF: 'IPD_STAFF',
  EMERGENCY_STAFF: 'EMERGENCY_STAFF',
  DEPARTMENT_MANAGER: 'DEPARTMENT_MANAGER',
  SUPPORT_STAFF: 'SUPPORT_STAFF',
  CUSTOM_ROLE: 'CUSTOM_ROLE',
  PATIENT: 'PATIENT',
  GUARDIAN: 'GUARDIAN',
};

export const DEPARTMENTS = [
  'General Medicine',
  'Cardiology',
  'Orthopedics',
  'Pediatrics',
  'Gynecology',
  'Nursing',
  'Reception',
  'Billing',
  'Laboratory',
  'CBC',
  'Pathology',
  'Radiology',
  'X-Ray',
  'MRI',
  'CT Scan',
  'Ultrasound',
  'Pharmacy',
  'OPD',
  'IPD',
  'Emergency',
  'Custom Department',
];

export const PATIENT_CATEGORIES = {
  GENERAL: 'GENERAL',
  VIP: 'VIP',
  CORPORATE: 'CORPORATE',
  STAFF: 'STAFF',
  INSURANCE: 'INSURANCE',
  BPL: 'BPL',
};

export const BED_STATUS = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  RESERVED: 'RESERVED',
  CLEANING: 'CLEANING',
  CLEANING_SANITIZING: 'CLEANING_SANITIZING',
  MAINTENANCE: 'MAINTENANCE',
  BLOCKED: 'BLOCKED',
  ISOLATION: 'ISOLATION',
};

export const WARD_TYPES = {
  GENERAL: 'GENERAL',
  MALE_WARD: 'MALE_WARD',
  FEMALE_WARD: 'FEMALE_WARD',
  ICU: 'ICU',
  NICU: 'NICU',
  PICU: 'PICU',
  EMERGENCY: 'EMERGENCY',
  MATERNITY: 'MATERNITY',
  POST_OPERATIVE: 'POST_OPERATIVE',
  PEDIATRIC: 'PEDIATRIC',
  ISOLATION: 'ISOLATION',
  PRIVATE: 'PRIVATE',
  SEMI_PRIVATE: 'SEMI_PRIVATE',
  DELUXE: 'DELUXE',
  CUSTOM: 'CUSTOM',
};

export const ROOM_TYPES = {
  SINGLE: 'SINGLE',
  TWIN_SHARING: 'TWIN_SHARING',
  TRIPLE_SHARING: 'TRIPLE_SHARING',
  FOUR_SHARING: 'FOUR_SHARING',
  MULTI_SHARING: 'MULTI_SHARING',
  GENERAL_WARD_ROOM: 'GENERAL_WARD_ROOM',
  PRIVATE: 'PRIVATE',
  SEMI_PRIVATE: 'SEMI_PRIVATE',
  DELUXE: 'DELUXE',
  SUITE: 'SUITE',
  ICU: 'ICU',
  NICU: 'NICU',
  ISOLATION: 'ISOLATION',
  EMERGENCY_OBSERVATION: 'EMERGENCY_OBSERVATION',
  CUSTOM: 'CUSTOM',
};

export const BED_TYPES = {
  NORMAL: 'NORMAL',
  ELECTRIC: 'ELECTRIC',
  ICU: 'ICU',
  VENTILATOR: 'VENTILATOR',
  PEDIATRIC: 'PEDIATRIC',
  MATERNITY: 'MATERNITY',
  ISOLATION: 'ISOLATION',
  EMERGENCY: 'EMERGENCY',
  CUSTOM: 'CUSTOM',
};

export const GENDER_RESTRICTIONS = {
  ANY: 'ANY',
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  CHILD: 'CHILD',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
};


export const REQUEST_TYPES = {
  WATER: 'WATER',
  FOOD: 'FOOD',
  BLANKET: 'BLANKET',
  PILLOW: 'PILLOW',
  CLEANING: 'CLEANING',
  RESTROOM: 'RESTROOM',
  WHEELCHAIR: 'WHEELCHAIR',
  BED_POSITION: 'BED_POSITION',
  MEDICINE: 'MEDICINE',
  NURSE: 'NURSE',
  ATTENDANT: 'ATTENDANT',
  IV_DRIP: 'IV_DRIP',
  URINE_BAG: 'URINE_BAG',
  CATHETER: 'CATHETER',
  DRAINAGE_TUBE: 'DRAINAGE_TUBE',
  OXYGEN: 'OXYGEN',
  EMERGENCY: 'EMERGENCY',
};

export const REQUEST_STATUS = {
  PENDING: 'PENDING',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  EN_ROUTE: 'EN_ROUTE',
  COMPLETED: 'COMPLETED',
  ESCALATED_L1: 'ESCALATED_L1',
  ESCALATED_L2: 'ESCALATED_L2',
  ESCALATED_L3: 'ESCALATED_L3',
  CANCELLED: 'CANCELLED',
};

export const CODE_TYPES = {
  CODE_BLUE: 'CODE_BLUE',
  CODE_RED: 'CODE_RED',
  TRAUMA: 'TRAUMA',
};

export const EMERGENCY_STATUS = {
  ACTIVE: 'ACTIVE',
  RESPONDING: 'RESPONDING',
  ON_SITE: 'ON_SITE',
  RESOLVED: 'RESOLVED',
  CANCELLED: 'CANCELLED',
};

export const PAYMENT_MODES = {
  CASH: 'CASH',
  CARD: 'CARD',
  UPI: 'UPI',
  NET_BANKING: 'NET_BANKING',
  TPA: 'TPA',
  WALLET: 'WALLET',
};

export const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  VOID: 'VOID',
  CANCELLED: 'CANCELLED',
  DELETED: 'DELETED',
};
