export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HOSPITAL_ADMIN: 'HOSPITAL_ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  NURSE_INCHARGE: 'NURSE_INCHARGE',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  LAB_TECH: 'LAB_TECH',
  RADIOLOGIST: 'RADIOLOGIST',
  CASHIER: 'CASHIER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  HR_MANAGER: 'HR_MANAGER',
  PATIENT: 'PATIENT',
  GUARDIAN: 'GUARDIAN',
};

export const ROLE_NAMES = {
  SUPER_ADMIN: 'System Super Admin',
  HOSPITAL_ADMIN: 'Hospital Administrator',
  DOCTOR: 'Doctor / Consultant',
  NURSE: 'Nurse / Ward Staff',
  NURSE_INCHARGE: 'Nurse In-Charge',
  RECEPTIONIST: 'Receptionist / Front Desk',
  PHARMACIST: 'Pharmacist',
  LAB_TECH: 'Lab Technician / Pathologist',
  RADIOLOGIST: 'Radiologist',
  CASHIER: 'Billing Clerk / Cashier',
  INVENTORY_MANAGER: 'Inventory Manager',
  HR_MANAGER: 'HR / Payroll Manager',
  PATIENT: 'Patient Portal',
  GUARDIAN: 'Guardian Portal',
};

export const ROLE_NAVIGATION = {
  SUPER_ADMIN: [
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  HOSPITAL_ADMIN: [
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  DOCTOR: [
    { title: 'Clinical EMR Desk', path: '/doctor/dashboard', icon: 'Stethoscope' },
    { title: 'Queued Patients', path: '/doctor/dashboard?tab=LIVE', icon: 'Hourglass' },
    { title: 'Completed Visits', path: '/doctor/dashboard?tab=COMPLETED', icon: 'CheckCircle2' },
    { title: 'Department Responses', path: '/doctor/dashboard?tab=DEPT_RESPONSES', icon: 'FileCheck2' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  NURSE: [
    { title: 'Nursing Workstation', path: '/nursing/dashboard', icon: 'Activity' },
    { title: 'Bed Matrix Console', path: '/nursing/beds', icon: 'Bed' },
    { title: 'In-Bed Patient Requests', path: '/nursing/requests', icon: 'Bell' },
    { title: 'Vitals & MAR Log', path: '/nursing/vitals', icon: 'ClipboardList' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  NURSE_INCHARGE: [
    { title: 'Ward In-Charge Desk', path: '/nurse-incharge/dashboard', icon: 'ShieldCheck' },
    { title: 'IPD Requisitions & Allocations', path: '/nurse-incharge/dashboard?tab=REQUISITIONS', icon: 'BedDouble' },
    { title: 'Admitted Patients & Bed Occupancy', path: '/nurse-incharge/dashboard?tab=ADMITTED', icon: 'UserCheck' },
    { title: 'Hospital Ward & Bed Matrix', path: '/nurse-incharge/dashboard?tab=BEDS', icon: 'LayoutGrid' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  RECEPTIONIST: [
    { title: 'Reception Desk', path: '/reception/dashboard', icon: 'LayoutDashboard' },
    { title: 'Registered Patients (Awaiting Token)', path: '/reception/registered-patients?tab=REGISTERED', icon: 'UserCheck' },
    { title: 'Queued / Active OPD', path: '/reception/registered-patients?tab=QUEUED', icon: 'Hourglass' },
    { title: 'Completed & Billed', path: '/reception/registered-patients?tab=COMPLETED', icon: 'CheckCircle2' },
    { title: 'All Hospital Patients', path: '/reception/registered-patients?tab=ALL', icon: 'Users' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  PHARMACIST: [
    { title: 'Pharmacy Desk', path: '/pharmacy/dashboard', icon: 'Pill' },
    { title: 'Prescription Queue', path: '/pharmacy/dispense-queue', icon: 'Clock' },
    { title: 'FEFO Stock Manager', path: '/pharmacy/stock', icon: 'Boxes' },
    { title: 'Expiry Alerts', path: '/pharmacy/expiry-alerts', icon: 'AlertTriangle' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  LAB_TECH: [
    { title: 'Laboratory Desk', path: '/laboratory/dashboard', icon: 'TestTube' },
    { title: 'Sample Intake & Barcodes', path: '/laboratory/dashboard?tab=SAMPLES', icon: 'QrCode' },
    { title: 'Result Entry Workbench', path: '/laboratory/dashboard?tab=RESULTS', icon: 'FileSpreadsheet' },
    { title: 'Report Sign-Off', path: '/laboratory/dashboard?tab=REPORTS', icon: 'CheckCircle2' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  RADIOLOGIST: [
    { title: 'Radiology Desk', path: '/radiology/dashboard', icon: 'FileCheck' },
    { title: 'PACS DICOM Viewer', path: '/radiology/dashboard?tab=DICOM', icon: 'FileImage' },
    { title: 'Diagnostic Reports', path: '/radiology/dashboard?tab=REPORTS', icon: 'FileCheck2' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  CASHIER: [
    { title: 'Central Billing Desk', path: '/billing/dashboard', icon: 'CreditCard' },
    { title: 'Receipts & Payment History', path: '/billing/dashboard?tab=RECEIPTS', icon: 'Receipt' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  INVENTORY_MANAGER: [
    { title: 'Inventory Dashboard', path: '/inventory/dashboard', icon: 'Package' },
    { title: 'Ward Indent Requests', path: '/inventory/indents', icon: 'Truck' },
    { title: 'Purchase Orders Console', path: '/inventory/purchase-orders', icon: 'ShoppingCart' },
    { title: 'Stock Reorder Alerts', path: '/inventory/reorder-alerts', icon: 'AlertCircle' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  HR_MANAGER: [
    { title: 'HR Management Desk', path: '/hr/dashboard', icon: 'UserCheck' },
    { title: 'Duty Rostering Engine', path: '/hr/roster', icon: 'CalendarDays' },
    { title: 'Biometric Attendance', path: '/hr/attendance', icon: 'Fingerprint' },
    { title: 'Monthly Payroll', path: '/hr/payroll', icon: 'IndianRupee' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  PATIENT: [
    { title: 'My Health Portal', path: '/patient-portal/dashboard', icon: 'User' },
    { title: 'Medical Records & RX', path: '/patient-portal/records', icon: 'FileText' },
    { title: 'Invoices & Payments', path: '/patient-portal/bills', icon: 'Receipt' },
    { title: 'Request Room Amenity', path: '/patient-portal/request-amenity', icon: 'Bell' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
  GUARDIAN: [
    { title: 'Guardian Portal', path: '/guardian/dashboard', icon: 'Shield' },
    { title: 'Patient Vitals Monitor', path: '/guardian/vitals', icon: 'HeartPulse' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert' },
  ],
};
