export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HOSPITAL_ADMIN: 'HOSPITAL_ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  NURSE_INCHARGE: 'NURSE_INCHARGE',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  LAB_TECH: 'LAB_TECH',
  RADIOLOGIST: 'RADIOLOGIST',
  CASHIER: 'CASHIER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  HR_MANAGER: 'HR_MANAGER',
  BILLING_STAFF: 'BILLING_STAFF',
  LABORATORY_STAFF: 'LABORATORY_STAFF',
  RADIOLOGY_STAFF: 'RADIOLOGY_STAFF',
  PHARMACY_STAFF: 'PHARMACY_STAFF',
  OPD_STAFF: 'OPD_STAFF',
  IPD_STAFF: 'IPD_STAFF',
  EMERGENCY_STAFF: 'EMERGENCY_STAFF',
  DEPARTMENT_MANAGER: 'DEPARTMENT_MANAGER',
  SUPPORT_STAFF: 'SUPPORT_STAFF',
  CUSTOM_ROLE: 'CUSTOM_ROLE',
  PATIENT: 'PATIENT',
  GUARDIAN: 'GUARDIAN',
};

export const ROLE_NAMES = {
  SUPER_ADMIN: 'System Super Admin',
  HOSPITAL_ADMIN: 'Hospital Administrator',
  DOCTOR: 'Doctor',
  NURSE: 'Nurse',
  NURSE_INCHARGE: 'Nurse In-Charge',
  RECEPTIONIST: 'Receptionist',
  PHARMACIST: 'Pharmacist',
  LAB_TECH: 'Lab Technician',
  RADIOLOGIST: 'Radiologist',
  CASHIER: 'Billing Cashier',
  BILLING_STAFF: 'Billing Staff',
  LABORATORY_STAFF: 'Laboratory Staff',
  RADIOLOGY_STAFF: 'Radiology Staff',
  PHARMACY_STAFF: 'Pharmacy Staff',
  OPD_STAFF: 'OPD Staff',
  IPD_STAFF: 'IPD Staff',
  EMERGENCY_STAFF: 'Emergency Staff',
  DEPARTMENT_MANAGER: 'Department Manager',
  SUPPORT_STAFF: 'Support Staff',
  CUSTOM_ROLE: 'Custom Role',
  INVENTORY_MANAGER: 'Inventory Manager',
  HR_MANAGER: 'HR / Payroll Manager',
  PATIENT: 'Patient Portal',
  GUARDIAN: 'Guardian Portal',
};

export const DEPARTMENTS = [
  'General Medicine',
  'Cardiology',
  'Orthopedics',
  'Pediatrics',
  'Gynecology',
  'Nursing',
  'Reception',
  'Billing',
  'Laboratory',
  'CBC',
  'Pathology',
  'Radiology',
  'X-Ray',
  'MRI',
  'CT Scan',
  'Ultrasound',
  'Pharmacy',
  'OPD',
  'IPD',
  'Emergency',
  'Custom Department',
];

export const MODULE_ACTION_MATRIX = {
  dashboard: {
    label: 'Dashboard Overview',
    actions: { view: 'View Dashboard' },
  },
  patientRegistration: {
    label: 'Patient Registration',
    actions: { view: 'View Registration Desk', create: 'Register Patient', edit: 'Edit Patient Details', delete: 'Delete Patient Record', print: 'Print Registration Form', export: 'Export Registration List' },
  },
  patients: {
    label: 'Patients Management',
    actions: { view: 'View Patients', create: 'Add Patient', edit: 'Edit Patient', delete: 'Delete Patient', print: 'Print Details', export: 'Export Records' },
  },
  tokens: {
    label: 'Tokens and Queue Management',
    actions: { view: 'View Tokens', create: 'Generate Token', edit: 'Edit Token', cancel: 'Cancel Token', assign: 'Assign Doctor', moveQueue: 'Move Queue Position', print: 'Print Token', markCompleted: 'Mark Consultation Completed' },
  },
  appointments: {
    label: 'Appointments',
    actions: { view: 'View Appointments', create: 'Create Appointment', edit: 'Edit Appointment', cancel: 'Cancel Appointment', book: 'Book Slot', doctorAvailability: 'View Doctor Availability' },
  },
  doctorConsultation: {
    label: 'Doctor Consultation',
    actions: { view: 'View Assigned Patients', startConsultation: 'Start Consultation', diagnose: 'Add Diagnosis', prescribe: 'Add Prescription', requestLab: 'Request Laboratory Test', requestRadiology: 'Request Radiology Test', addTreatment: 'Add Treatment Plan', finalize: 'Finalize Consultation', viewCompletedVisits: 'View Completed Visits' },
  },
  diagnosis: {
    label: 'Diagnosis & EMR',
    actions: { view: 'View Diagnoses', create: 'Add Diagnosis Entry', edit: 'Edit Diagnosis' },
  },
  prescription: {
    label: 'Prescription',
    actions: { view: 'View Prescriptions', create: 'Create Prescription', edit: 'Edit Prescription', dispense: 'Dispense Medicine' },
  },
  treatment: {
    label: 'Treatment & Care',
    actions: { view: 'View Treatments', create: 'Add Treatment Note', edit: 'Update Treatment' },
  },
  nursing: {
    label: 'Nursing & Ward Care',
    actions: { view: 'View Nursing Console', viewInstructions: 'View Doctor Instructions', viewTreatment: 'View Treatment Details', viewMedicineSchedule: 'View Medicine Schedule', updateVitals: 'Update Patient Vitals', addNotes: 'Add Nursing Notes', administerInjection: 'Administer Injections', manageTasks: 'Manage Nursing Tasks', handleRequests: 'Handle Patient Requests', respondEmergency: 'Respond to Emergencies', manageWardAssignments: 'Manage Ward Assignments' },
  },
  laboratory: {
    label: 'Laboratory & Pathology',
    actions: { view: 'View Laboratory Desk', accept: 'Accept Sample', edit: 'Edit Test Results', upload: 'Upload Diagnostic Report', print: 'Print Report', requestTest: 'Create Lab Request' },
  },
  radiology: {
    label: 'Radiology & Imaging',
    actions: { view: 'View Radiology Desk', accept: 'Accept Imaging Request', edit: 'Edit Scan Report', upload: 'Upload DICOM / Image', print: 'Print DICOM Report', requestTest: 'Create Imaging Request' },
  },
  pharmacy: {
    label: 'Pharmacy Store',
    actions: { view: 'View Pharmacy Desk', create: 'Add Stock Item', edit: 'Edit Batch Details', dispense: 'Dispense Prescriptions', print: 'Print Medicine Labels' },
  },
  billing: {
    label: 'Billing & Payments',
    actions: { view: 'View Finalized Bills', create: 'Create Bill', addCharges: 'Add Charges', editCharges: 'Edit Charges', removeCharges: 'Remove Charges', applyDiscount: 'Apply Discount', receivePayment: 'Accept Payment', generateInvoice: 'Generate Invoice', printReceipt: 'Print Receipt', processRefund: 'Process Refund', exportReport: 'Export Financial Report' },
  },
  opd: {
    label: 'OPD Management',
    actions: { view: 'View OPD Desk', manage: 'Manage OPD Workflows' },
  },
  ipd: {
    label: 'IPD Management',
    actions: { view: 'View IPD Ward Desk', manage: 'Manage Inpatient Allocations' },
  },
  emergency: {
    label: 'Emergency Care',
    actions: { view: 'View Emergency Console', create: 'Trigger Emergency Alert', respond: 'Respond to Code Blue / Emergency', resolve: 'Resolve Emergency' },
  },
  departments: {
    label: 'Departments Management',
    actions: { view: 'View Departments', manage: 'Manage Department Settings' },
  },

  reports: {
    label: 'Reports & Analytics',
    actions: { view: 'View Operational Reports', generate: 'Generate Analytics Report', export: 'Export Reports (PDF/CSV)' },
  },
  notifications: {
    label: 'Notifications',
    actions: { view: 'Receive & View Notifications' },
  },
  auditLogs: {
    label: 'Audit Logs',
    actions: { view: 'Inspect System Audit Logs' },
  },
  hospitalSettings: {
    label: 'Hospital Settings',
    actions: { view: 'View Settings', edit: 'Modify Tariff & Hospital Config' },
  },
};

export const ROLE_NAVIGATION = {
  SUPER_ADMIN: [
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  HOSPITAL_ADMIN: [
    { title: 'Dashboard Overview', path: '/hospital-admin/dashboard', icon: 'LayoutDashboard', module: 'dashboard' },
    { title: 'Departments Setup', path: '/hospital-admin/departments', icon: 'GitFork', module: 'departments' },
    { title: 'Roles & Permissions', path: '/hospital-admin/staff?tab=permissions', icon: 'KeyRound', module: 'staffManagement' },
    { title: 'Patients (Management)', path: '/hospital-admin/patients-management', icon: 'Users', module: 'patients' },
    { title: 'Doctors (Management)', path: '/hospital-admin/doctors-management', icon: 'Stethoscope', module: 'doctorConsultation' },
    { title: 'Nurses (Management)', path: '/hospital-admin/nurses-management', icon: 'Activity', module: 'nursing' },
    { title: 'Reception (Management)', path: '/hospital-admin/reception-management', icon: 'ConciergeBell', module: 'reception' },
    { title: 'Laboratory (Management)', path: '/hospital-admin/laboratory-management', icon: 'TestTube', module: 'laboratory' },
    { title: 'Radiology (Management)', path: '/hospital-admin/radiology-management', icon: 'Scan', module: 'radiology' },
    { title: 'Pharmacy (Management)', path: '/hospital-admin/pharmacy-management', icon: 'Pill', module: 'pharmacy' },
    { title: 'Billing (Management)', path: '/hospital-admin/billing-management', icon: 'CreditCard', module: 'billing' },
    { title: 'OPD (Management)', path: '/hospital-admin/opd-management', icon: 'ClipboardList', module: 'opd' },
    { title: 'IPD (Management)', path: '/hospital-admin/ipd-management', icon: 'BedDouble', module: 'ipd' },
    { title: 'Emergency (Management)', path: '/hospital-admin/emergency-management', icon: 'ShieldAlert', module: 'emergency' },
    { title: 'Reports & Analytics', path: '/hospital-admin/reports', icon: 'BarChart3', module: 'reports' },
    { title: 'Notifications', path: '/hospital-admin/dashboard?tab=notifications', icon: 'Bell', module: 'notifications' },
    { title: 'Audit Logs', path: '/hospital-admin/reports?tab=audit', icon: 'FileText', module: 'auditLogs' },
    { title: 'Plan Details', path: '/hospital-admin/plan-details', icon: 'BadgeCheck', module: 'dashboard' },
    { title: 'Usage & Limits', path: '/hospital-admin/usage-limits', icon: 'Gauge', module: 'dashboard' },
    { title: 'Hospital Settings', path: '/hospital-admin/tariffs', icon: 'Settings', module: 'hospitalSettings' },
  ],
  DOCTOR: [
    { title: 'Appointments Desk', path: '/doctor/dashboard?tab=LIVE', icon: 'Calendar', module: 'appointments' },
    { title: 'Clinical EMR Desk', path: '/doctor/dashboard', icon: 'Stethoscope', module: 'doctorConsultation' },
    { title: 'Completed Visits', path: '/doctor/dashboard?tab=COMPLETED', icon: 'CheckCircle2', module: 'doctorConsultation' },
    { title: 'Department Request & Response Tracker', path: '/doctor/dashboard?tab=DEPT_RESPONSES', icon: 'FileCheck2', module: 'doctorConsultation' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  NURSE: [
    { title: 'Nursing Workstation', path: '/nursing/dashboard', icon: 'Activity', module: 'nursing' },
    { title: 'Bed Matrix Console', path: '/nursing/beds', icon: 'Bed', module: 'nursing' },
    { title: 'In-Bed Patient Requests', path: '/nursing/requests', icon: 'Bell', module: 'nursing' },
    { title: 'Vitals & MAR Log', path: '/nursing/vitals', icon: 'ClipboardList', module: 'nursing' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  NURSE_INCHARGE: [
    { title: 'Ward In-Charge Desk', path: '/nurse-incharge/dashboard', icon: 'ShieldCheck', module: 'ipd' },
    { title: 'IPD Requisitions & Allocations', path: '/nurse-incharge/dashboard?tab=REQUISITIONS', icon: 'BedDouble', module: 'ipd' },
    { title: 'Admitted Patients & Bed Occupancy', path: '/nurse-incharge/dashboard?tab=ADMITTED', icon: 'UserCheck', module: 'ipd' },
    { title: 'Hospital Ward & Bed Matrix', path: '/nurse-incharge/dashboard?tab=BEDS', icon: 'LayoutGrid', module: 'ipd' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  RECEPTIONIST: [
    { title: 'Reception Desk', path: '/reception/dashboard', icon: 'LayoutDashboard', module: 'appointments' },
    { title: 'Tokens & Queue', path: '/reception/tokens', icon: 'Ticket', module: 'tokens' },
    { title: 'Registered Patients', path: '/reception/registered-patients?tab=REGISTERED', icon: 'UserCheck', module: 'patients' },
    { title: 'Queued / Active OPD', path: '/reception/registered-patients?tab=QUEUED', icon: 'Hourglass', module: 'opd' },
    { title: 'Completed & Billed', path: '/reception/registered-patients?tab=COMPLETED', icon: 'CheckCircle2', module: 'patients' },
    { title: 'All Hospital Patients', path: '/reception/registered-patients?tab=ALL', icon: 'Users', module: 'patients' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  PHARMACIST: [
    { title: 'Pharmacy Desk', path: '/pharmacy/dashboard', icon: 'Pill', module: 'pharmacy' },
    { title: 'Prescription Queue', path: '/pharmacy/dispense-queue', icon: 'Clock', module: 'pharmacy' },
    { title: 'FEFO Stock Manager', path: '/pharmacy/stock', icon: 'Boxes', module: 'pharmacy' },
    { title: 'Expiry Alerts', path: '/pharmacy/expiry-alerts', icon: 'AlertTriangle', module: 'pharmacy' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  PHARMACY_STAFF: [
    { title: 'Pharmacy Desk', path: '/pharmacy/dashboard', icon: 'Pill', module: 'pharmacy' },
    { title: 'Prescription Queue', path: '/pharmacy/dispense-queue', icon: 'Clock', module: 'pharmacy' },
    { title: 'FEFO Stock Manager', path: '/pharmacy/stock', icon: 'Boxes', module: 'pharmacy' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  LAB_TECH: [
    { title: 'Laboratory Desk', path: '/laboratory/dashboard', icon: 'TestTube', module: 'laboratory' },
    { title: 'Sample Intake & Barcodes', path: '/laboratory/dashboard?tab=SAMPLES', icon: 'QrCode', module: 'laboratory' },
    { title: 'Result Entry Workbench', path: '/laboratory/dashboard?tab=RESULTS', icon: 'FileSpreadsheet', module: 'laboratory' },
    { title: 'Report Sign-Off', path: '/laboratory/dashboard?tab=REPORTS', icon: 'CheckCircle2', module: 'laboratory' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  LABORATORY_STAFF: [
    { title: 'Laboratory Desk', path: '/laboratory/dashboard', icon: 'TestTube', module: 'laboratory' },
    { title: 'Sample Intake & Barcodes', path: '/laboratory/dashboard?tab=SAMPLES', icon: 'QrCode', module: 'laboratory' },
    { title: 'Result Entry Workbench', path: '/laboratory/dashboard?tab=RESULTS', icon: 'FileSpreadsheet', module: 'laboratory' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  RADIOLOGIST: [
    { title: 'Radiology Desk', path: '/radiology/dashboard', icon: 'FileCheck', module: 'radiology' },
    { title: 'PACS DICOM Viewer', path: '/radiology/dashboard?tab=DICOM', icon: 'FileImage', module: 'radiology' },
    { title: 'Diagnostic Reports', path: '/radiology/dashboard?tab=REPORTS', icon: 'FileCheck2', module: 'radiology' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  RADIOLOGY_STAFF: [
    { title: 'Radiology Desk', path: '/radiology/dashboard', icon: 'FileCheck', module: 'radiology' },
    { title: 'PACS DICOM Viewer', path: '/radiology/dashboard?tab=DICOM', icon: 'FileImage', module: 'radiology' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  CASHIER: [
    { title: 'Central Billing Desk', path: '/billing/dashboard', icon: 'CreditCard', module: 'billing' },
    { title: 'Receipts & Payment History', path: '/billing/dashboard?tab=RECEIPTS', icon: 'Receipt', module: 'billing' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  BILLING_STAFF: [
    { title: 'Central Billing Desk', path: '/billing/dashboard', icon: 'CreditCard', module: 'billing' },
    { title: 'Receipts & Payment History', path: '/billing/dashboard?tab=RECEIPTS', icon: 'Receipt', module: 'billing' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  OPD_STAFF: [
    { title: 'OPD Queued Desk', path: '/reception/registered-patients?tab=QUEUED', icon: 'ClipboardList', module: 'opd' },
    { title: 'Tokens & Queue Calling', path: '/reception/tokens', icon: 'Ticket', module: 'tokens' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  IPD_STAFF: [
    { title: 'IPD Inpatient Desk', path: '/nurse-incharge/dashboard', icon: 'BedDouble', module: 'ipd' },
    { title: 'Bed Matrix Console', path: '/nursing/beds', icon: 'Bed', module: 'nursing' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  EMERGENCY_STAFF: [
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  DEPARTMENT_MANAGER: [
    { title: 'Department Overview', path: '/hospital-admin/departments', icon: 'GitFork', module: 'departments' },
    { title: 'Reports & Analytics', path: '/hospital-admin/reports', icon: 'BarChart3', module: 'reports' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  SUPPORT_STAFF: [
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  CUSTOM_ROLE: [
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  INVENTORY_MANAGER: [
    { title: 'Inventory Dashboard', path: '/inventory/dashboard', icon: 'Package', module: 'inventory' },
    { title: 'Ward Indent Requests', path: '/inventory/indents', icon: 'Truck', module: 'inventory' },
    { title: 'Purchase Orders Console', path: '/inventory/purchase-orders', icon: 'ShoppingCart', module: 'inventory' },
    { title: 'Stock Reorder Alerts', path: '/inventory/reorder-alerts', icon: 'AlertCircle', module: 'inventory' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  HR_MANAGER: [
    { title: 'HR Management Desk', path: '/hr/dashboard', icon: 'UserCheck', module: 'hr' },
    { title: 'Duty Rostering Engine', path: '/hr/roster', icon: 'CalendarDays', module: 'hr' },
    { title: 'Biometric Attendance', path: '/hr/attendance', icon: 'Fingerprint', module: 'hr' },
    { title: 'Monthly Payroll', path: '/hr/payroll', icon: 'IndianRupee', module: 'hr' },
    { title: 'Emergency Console', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  PATIENT: [
    { title: 'Dashboard', path: '/patient-portal/dashboard', icon: 'LayoutDashboard', module: 'patientPortal' },
    { title: 'My Profile', path: '/patient-portal/profile', icon: 'User', module: 'patientPortal' },
    { title: 'My Tokens', path: '/patient-portal/tokens', icon: 'Ticket', module: 'patientPortal' },
    { title: 'Current Treatment', path: '/patient-portal/treatment', icon: 'Activity', module: 'patientPortal' },
    { title: 'Treatment History', path: '/patient-portal/history', icon: 'Clock', module: 'patientPortal' },
    { title: 'Doctor Instructions', path: '/patient-portal/doctor-instructions', icon: 'Stethoscope', module: 'patientPortal' },
    { title: 'Prescriptions', path: '/patient-portal/prescriptions', icon: 'Pill', module: 'patientPortal' },
    { title: 'Laboratory Reports', path: '/patient-portal/lab-reports', icon: 'TestTube', module: 'patientPortal' },
    { title: 'Radiology Reports', path: '/patient-portal/radiology-reports', icon: 'FileImage', module: 'patientPortal' },
    { title: 'Admission & Room Details', path: '/patient-portal/admission', icon: 'BedDouble', module: 'patientPortal' },
    { title: 'Assigned Care Team', path: '/patient-portal/care-team', icon: 'Users', module: 'patientPortal' },
    { title: 'Patient Care Requests', path: '/patient-portal/requests', icon: 'Bell', module: 'patientPortal' },
    { title: 'Billing and Payments', path: '/patient-portal/billing', icon: 'Receipt', module: 'patientPortal' },
    { title: 'Discharge Summary', path: '/patient-portal/discharge', icon: 'FileText', module: 'patientPortal' },
    { title: 'Emergency Assistance', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
  GUARDIAN: [
    { title: 'Dashboard', path: '/guardian-portal/dashboard', icon: 'LayoutDashboard', module: 'guardianPortal' },
    { title: 'Patient Overview', path: '/guardian-portal/overview', icon: 'UserCheck', module: 'guardianPortal' },
    { title: 'Current Treatment', path: '/guardian-portal/treatment', icon: 'Activity', module: 'guardianPortal' },
    { title: 'Treatment History', path: '/guardian-portal/history', icon: 'Clock', module: 'guardianPortal' },
    { title: 'Doctor Updates', path: '/guardian-portal/doctor-updates', icon: 'Stethoscope', module: 'guardianPortal' },
    { title: 'Prescriptions', path: '/guardian-portal/prescriptions', icon: 'Pill', module: 'guardianPortal' },
    { title: 'Lab & Radiology Reports', path: '/guardian-portal/reports', icon: 'FileSpreadsheet', module: 'guardianPortal' },
    { title: 'Admission Details', path: '/guardian-portal/admission', icon: 'BedDouble', module: 'guardianPortal' },
    { title: 'Assigned Care Team', path: '/guardian-portal/care-team', icon: 'Users', module: 'guardianPortal' },
    { title: 'Patient Requests Monitor', path: '/guardian-portal/requests', icon: 'Bell', module: 'guardianPortal' },
    { title: 'Billing & Payments', path: '/guardian-portal/billing', icon: 'Receipt', module: 'guardianPortal' },
    { title: 'Discharge Summary', path: '/guardian-portal/discharge', icon: 'FileText', module: 'guardianPortal' },
    { title: 'Emergency Assistance', path: '/emergency', icon: 'ShieldAlert', module: 'emergency' },
  ],
};
